language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
    - rm -f composer.lock
    - composer install --prefer-dist --ignore-platform-reqs

git:
  depth: 5
